### ISSUE TITLE
你好，有没有试过连接蓝牙打印机？

### ISSUE THREAD

**Issue by AlexYuan** [lidong1665/wx_ble#1]
我现在write成功，但是不知道怎么把打印指令发送给打印机

**Comment by liuyiji** [comment]
这个需要看打印机指令协议，按照协议发送就可以的把


原始邮件
发件人:AlexYuannotifications@github.com
收件人:lidong1665/wx_blewx_ble@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年4月25日(周二) 17:03
主题:[lidong1665/wx_ble] 你好，有没有试过连接蓝牙打印机？ (#1)


我现在write成功，但是不知道怎么把打印指令发送给打印机

**Comment by lidong1665** [comment]
看看协议，指令可能不正确
